### ISSUE TITLE
Native video android

### ISSUE THREAD

**Issue by solidfox** [fan-ADN/nendSDK-react-native#1]
Hi!

We're working on a project in which we really wish to use native video ads on both Android and iOS in a React Native context. Any ideas on why this is not working and when / how this could be fixed?

Best,
Daniel

**Comment by fan-t-fukuoka** [comment]
@solidfox 

Thank you for your commented.

`Native video android` is still under development and it is unknown when it can be provided.
I will inform you when it is completed.

Best Regard,

**Comment by solidfox** [comment]
Much appreciated! You may consider us at Link-U highly interested in the progress!

**Comment by fan-t-fukuoka** [comment]
@solidfox

Thanks for waiting.

Released `Native video android` with [v0.0.2](https://www.npmjs.com/package/react-native-nend-bridger
).

Best Regards,

**Comment by solidfox** [comment]
Fantastic news! Thanks!
