### ISSUE TITLE
How to implement this SDK on iOS

### ISSUE THREAD

**Issue by khuyendev** [fan-ADN/nendSDK-react-native#4]
I tried implement SDK to my project in IOS, but I cant, because the document very spare.
I tried copied file which I thought it's necessary :
```
AwesomeProject-Bridging-Header.h
RCTNendAdViewManager.swift	
RCTNendAdViewManagerBridge.m	
RCTNendInterstitialAd.swift
RCTNendInterstitialAdBridge.m
RCTNendMediaViewManager.swift	
RCTNendMediaViewManagerBridge.m	
RCTNendNativeAd.swift
RCTNendNativeAdBridge.m
RCTNendUserFeature.swift
RCTNendUserFeatureBridge.m
RCTNendVideoAd.swift
RCTNendVideoAdBridge.m
RCTNendVideoNativeAd.swift
RCTNendVideoNativeAdBridge.m
```

Then i added this in PodFile:
` pod 'NendSDK_iOS'`

But I can't get working, When I run in simulator (iPhone 6).The console.log showing: "Native module is null"

Please update the document more clearly, or push the SDK into npmjs for easier implement

**Comment by ghost** [comment]
Hi @khuyendev ,

Could you give us about more details of your issue?

- Your build environment
  - version of `react-native`
  - version of `Xcode`
- Error log

Or could you send `Build project what has this issue` for us?

Best regards,

**Comment by khuyendev** [comment]
Hi @fan-w-suzuki 
My environment:
```
    "react": "16.8.3",
    "react-native": "0.59.8",
```
Xcode: 10.2
Log:
> react-native-nend-sdk` does not specify a Swift version and none of the targets (`Myproject`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.


I think NendSDK using swift 3.0 , and now it deprecated . Please upgrade SDK to swift 4.0

**Comment by ghost** [comment]
Hi, @khuyendev 

Thank you for replying.
>Xcode: 10.2
I think NendSDK using swift 3.0 , and now it deprecated 

Our `react-native` bridgings using Swift 3.0 yet.
Please check these workaround:

- Using Xcode 9.4.1 & Swift 3.0
- Or, if you want to use Swift 4.0, please modify your build project
    1. Upgrade swift version to `4.0` or later from your Xcode build settings
    2. Optimized Swift properties of all brigings classes for using `RCT_EXPORT_VIEW_PROPERTY`
