### ISSUE TITLE
Issue with Tabnavigation on Android

### ISSUE THREAD

**Issue by khuyendev** [fan-ADN/nendSDK-react-native#5]
Hello, again. I tried implement SDK on Android, then successfully. 
But I get a bug with TabNavigation using _createBottomTabNavigator_ from react-navigation:
**This is my case:**
1. I have 4 tabs, then Tab1 , i added an adView like this:
     ```
                        <AdView
                                spotId={spotId}
                                apiKey={apiKey}
                                adjustSize={true}
                                onAdLoaded={() => console.log('loading of ad is completed.')}
                                onAdFailedToLoad={(event: any) => console.log(`loading of ad is failed: ${event.nativeEvent.code}, ${event.nativeEvent.message}`)}
                                onAdClicked={() => console.log('ad clicked.')}
                                onInformationClicked={() => console.log('information button clicked.')}
                            />
2. It displayed success the banner 
3. I moved between any tabs (maybe Tab2, Tab3, Tab4) then back to Tab1
4. **The banner is missing at Tab1 and i can't get display back**

My react version:
```
  "react": "16.8.3",
  "react-native": "0.59.8",
  "react-navigation": "^3.0.7",
```

**Comment by ghost** [comment]
Hi @khuyendev 

The `AdView.js` that is current version works like this:
1. Just created height and width are `0` 
    https://github.com/fan-ADN/nendSDK-react-native/blob/39513733536b99eecb9a7c177ed3568deb314491/src/ad/AdView.js#L41

1. Then fixed banner size after loaded ad information
    https://github.com/fan-ADN/nendSDK-react-native/blob/39513733536b99eecb9a7c177ed3568deb314491/src/ad/AdView.js#L92

So if you want display banner ad when back to other pages, you should try to reload banner ad information.
Maybe it will be working.

And this repository is OSS. 
You can fork this repository and customize for your own reason.

Have a nice day!!
